---
- name: Install GPG and generate GPG key
  hosts: all
  become: true
  vars:
    gpg_real_name: "Your Name"
    gpg_email: "your-email@example.com"
    gpg_key_length: 4096
    gpg_expiry: "1y"  # Options: '0' for never expire, '1y' for one year, etc.
  tasks:
    - name: Install GPG package
      ansible.builtin.package:
        name: gnupg
        state: present

    - name: Generate GPG key input file
      ansible.builtin.copy:
        dest: /tmp/gpg-key-input.txt
        content: |
          %no-protection
          Key-Type: RSA
          Key-Length: {{ gpg_key_length }}
          Subkey-Type: RSA
          Subkey-Length: {{ gpg_key_length }}
          Name-Real: {{ gpg_real_name }}
          Name-Email: {{ gpg_email }}
          Expire-Date: {{ gpg_expiry }}
          %commit

    - name: Generate GPG key
      ansible.builtin.shell:
        cmd: "gpg --batch --generate-key /tmp/gpg-key-input.txt"
      args:
        creates: /root/.gnupg

    - name: List generated GPG keys
      ansible.builtin.shell:
        cmd: "gpg --list-keys"
      register: gpg_list_output

    - name: Display generated GPG keys
      ansible.builtin.debug:
        msg: "{{ gpg_list_output.stdout }}"

